### ISSUE TITLE
Can't connect to SBrick Plus

### ISSUE THREAD

**Issue by hmeyer** [vengit/pxt-sbrick#2]
I've just gotten a SBrick Plus, but I can't connect the micro:bit to the SBrick Plus via
`sbrick.connect("SBrick")`
It never gets to `bluetooth.onBluetoothConnected` or `sbrick.onConnected`, in both "No Pairing Required" and "JustWorks pairing".
Is there any pairing procedure I need to perform to initiate a connection on first use?

**Comment by netom** [comment]
We managed to reproduce this issue and working on it right now. The fix will involve new SBrick firmwares and a new release of this extension also. Expect a fix to come out early January. I apologize for this inconvenience.

**Comment by netom** [comment]
A fix has just been published. Version 1.0.6 and above should work OK.

**Comment by hmeyer** [comment]
Thanks for the super quick updates!

**Comment by hmeyer** [comment]
Happy New Year!
Any update on this? Or anything I can do to help?

**Comment by netom** [comment]
It's already possible to update to the new firmware on iOS. We're working on the Android application.

**Comment by wilburckwong** [comment]
I can't connect SBrick Plus with the micro:bit also. My Hardware Version is 11, Firmware Version is 25. pxt-sbrick version is 1.0.6. Can't be B, can't be S. It seems that the SBrick Plus does not initiate any connection to the micro:bit at all. Are there any new firmware and MakeCode extension out there to solve the problem? What I can do to help the troubleshooting?

**Comment by wilburckwong** [comment]
Well well well. I found the culprit!

Thanks to this [Web Bluetooth Sample](https://googlechrome.github.io/samples/web-bluetooth/device-disconnect.html?service=current_time&namePrefix=Red), I notice that with name prefix, I can search the SBrick, but not the exact name. So I add a space at the end, you know what, it found the SBrick.  It seems that it's the problem of the SBrick App (I'm using iOS) which add a space at the end of the type-in name.

**Comment by targetarchitecture** [comment]
@wilburckwong thanks for your post, I just got my SBrick today and changed the name to "Duck" (as in "The Duck Song"). My code wouldn't connect with 

`sbrick.connect("Duck")`

however using the Web Bluetooth Sample it connected with 

`sbrick.connect("Duck   ")`

I'm using the android app, with SBrick hardware version 13, firmware version 26.

**Comment by dsrc12** [comment]
It is now over three years since the issue of SBrick Plus not working with Makecode & microbit was reported and it still has not been fixed. I am using both SBrick & SBrick Plus. No problems with SBrick but SBrick Plus pairs and communicates with microbit but does not turn on motors. Also Wedo 1 sensors on Makecode with microbit using SBrick do not work.
